server:
  port: 12420

spring:
  application:
    name: catface_task
  profiles:
    active: dev # 默认开发环境，可选值dev(本地)和prod(生产环境)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE  # TIP 属性命名策略：默认是驼峰命名法，可以改成下划线命名法。
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.201.61.151:3306/spring-didi?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: didi
    password: didi12420

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: common.model.*
  type-handlers-package: com.catface_task.common.mapper.handler  # 类型处理器包。
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 xx_
    #table-prefix: xx_
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    #sql-Injector:   com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-delete-value: 1
    logic-not-delete-value: 0

# 文心一言配置
wenxin:
  api:
    key: your-wenxin-api-key
    secret: your-wenxin-api-secret
    chat-url: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions
    image-url: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/image_completions

# 百度语音配置
baidu:
  speech:
    api-key: your-speech-api-key
    secret-key: your-speech-secret-key
    asr-url: https://vop.baidu.com/server_api
    tts-url: https://tsn.baidu.com/text2audio

# 阿里云百炼通义千问VL配置
aliyun:
  dashscope:
    api-key: <api-key> # https://bailian.console.aliyun.com/?tab=home&utm_content=se_1021219533#/home
    base-url: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation
